/generatedValue/1: '1'
/generatedValue/2: '2'
/exceptions/1/NullPointerException: 'java.lang.NullPointerException: Error on first step!'
/generatedValue/3: '3'
/repeatedValue/1: '2'
/generatedValue/4: '4'
/exceptions/3/Exception: 'java.lang.ClassNotFoundException: Error on third step!'
/generatedValue/5: '5'
/repeatedValue/2: '4'
/generatedValue/6: '6'
/exceptions/5/ClassCastException: 'java.lang.ClassCastException: Error on fifth step!'
/generatedValue/7: '7'
/repeatedValue/3: '6'
/generatedValue/8: '8'
/exceptions/7/NullOutputException: 'org.restflow.exceptions.NullOutputException: Null data produced on non-nullable output ''outValue'' of actor ''CaughtActorExceptions.ThrowExceptionOnThirdStep.(inner
  bean)'''
/repeatedValue/4: '8'
