generatedValue/1: '10'
generatedValue/2: '20'
/Sub1/original: '10'
/Sub1/repeated: '10'
repeatedValue/1: '10'
generatedValue/3: '30'
/Sub2/original: '20'
/Sub2/repeated: '20'
repeatedValue/2: '20'
generatedValue/4: '40'
/Sub3/original: '30'
